apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: keycloak-dev

configMapGenerator:
  - name: env-cfg
    literals:
      - ENV=keycloak-dev
      - KEYCLOAK_HOSTNAME=keycloak-dev.apps-crc.testing
      - KEYCLOAK_URL=https://keycloak-dev.apps-crc.testing
      - GRAFANA_BASE_URL=https://grafana-grafana.apps-crc.testing
      - ZABBIX_BASE_URL=https://zabbix-zabbix.apps-crc.testing
      - SERVICE_NAME=keycloak-dev-service

replacements:
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.ENV
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
      - select:
          kind: OperatorGroup
        fieldPaths:
          - spec.targetNamespaces.0
      - select:
          kind: Keycloak
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.KEYCLOAK_HOSTNAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths:
          - spec.hostname.hostname
      - select:
          kind: Route
          name: keycloak
        fieldPaths:
          - spec.host
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.KEYCLOAK_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=KEYCLOAK_URL].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.GRAFANA_BASE_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=GRAFANA_BASE_URL].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.ZABBIX_BASE_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=ZABBIX_BASE_URL].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths:
          - spec.telemetry.serviceName
      - select:
          kind: Route
          name: keycloak
        fieldPaths:
          - spec.to.name

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: keycloak-desenvolvimento
      app.kubernetes.io/component: identity
      app.kubernetes.io/part-of: platform
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: desenvolvimento
    includeSelectors: false
