apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: keycloak-producao

configMapGenerator:
  - name: env-cfg
    literals:
      - ENV=keycloak-producao
      - KEYCLOAK_HOSTNAME=keycloak-producao.apps.example.invalid
      - KEYCLOAK_URL=https://keycloak-producao.apps.example.invalid
      - GRAFANA_BASE_URL=https://grafana-producao.apps.example.invalid
      - ZABBIX_BASE_URL=https://zabbix-producao.apps.example.invalid
      - SERVICE_NAME=keycloak-producao-service
      - PYROSCOPE_LABELS=service_name=keycloak-producao-service,service_namespace=keycloak-producao,namespace=keycloak-producao,deployment_environment_name=producao

replacements:
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.ENV
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
      - select:
          kind: OperatorGroup
        fieldPaths:
          - spec.targetNamespaces.0
      - select:
          kind: Keycloak
        fieldPaths:
          - metadata.name
      - select:
          kind: ServiceMonitor
          name: rhbk-service-monitor
        fieldPaths:
          - spec.selector.matchLabels.app\.kubernetes\.io/instance
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.KEYCLOAK_HOSTNAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths: [spec.hostname.hostname]
      - select:
          kind: Route
          name: keycloak
        fieldPaths: [spec.host]
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths:
          - spec.telemetry.serviceName
          - spec.env.[name=PYROSCOPE_APPLICATION_NAME].value
      - select:
          kind: Route
          name: keycloak
        fieldPaths: [spec.to.name]
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.PYROSCOPE_LABELS
    targets:
      - select:
          kind: Keycloak
        fieldPaths:
          - spec.env.[name=PYROSCOPE_LABELS].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.KEYCLOAK_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=KEYCLOAK_URL].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.GRAFANA_BASE_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=GRAFANA_BASE_URL].value
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.ZABBIX_BASE_URL
    targets:
      - select:
          kind: Job
          name: keycloak-config-cli-observability
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-config-cli].env.[name=ZABBIX_BASE_URL].value

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: keycloak-producao
      app.kubernetes.io/component: identity
      app.kubernetes.io/part-of: platform
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: producao
    includeSelectors: false
