apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-observability-realm
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  observability-realm.json: |
    {
      "realm": "observability",
      "enabled": true,
      "displayName": "Observability",
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "rememberMe": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "sslRequired": "external",

      "roles": {
        "realm": [
          {
            "name": "grafana_grafana_admin",
            "description": "Grafana global server administrator"
          },
          {
            "name": "grafana_admin",
            "description": "Grafana organization administrator"
          },
          {
            "name": "grafana_editor",
            "description": "Grafana editor"
          },
          {
            "name": "grafana_viewer",
            "description": "Grafana viewer"
          },
          {
            "name": "zabbix_super_admin",
            "description": "Zabbix Super admin role"
          },
          {
            "name": "zabbix_admin",
            "description": "Zabbix Admin role"
          },
          {
            "name": "zabbix_user",
            "description": "Zabbix User role"
          },
          {
            "name": "zabbix_guest",
            "description": "Zabbix Guest role"
          }
        ]
      },
      "groups": [
        {
          "name": "observability",
          "path": "/observability",
          "subGroups": [
            {
              "name": "grafana-grafana-admins",
              "path": "/observability/grafana-grafana-admins",
              "realmRoles": [
                "grafana_grafana_admin"
              ]
            },
            {
              "name": "grafana-admins",
              "path": "/observability/grafana-admins",
              "realmRoles": [
                "grafana_admin"
              ]
            },
            {
              "name": "grafana-editors",
              "path": "/observability/grafana-editors",
              "realmRoles": [
                "grafana_editor"
              ]
            },
            {
              "name": "grafana-viewers",
              "path": "/observability/grafana-viewers",
              "realmRoles": [
                "grafana_viewer"
              ]
            },
            {
              "name": "zabbix-super-admins",
              "path": "/observability/zabbix-super-admins",
              "realmRoles": [
                "zabbix_super_admin"
              ]
            },
            {
              "name": "zabbix-admins",
              "path": "/observability/zabbix-admins",
              "realmRoles": [
                "zabbix_admin"
              ]
            },
            {
              "name": "zabbix-users",
              "path": "/observability/zabbix-users",
              "realmRoles": [
                "zabbix_user"
              ]
            },
            {
              "name": "zabbix-guests",
              "path": "/observability/zabbix-guests",
              "realmRoles": [
                "zabbix_guest"
              ]
            }
          ]
        }
      ],
      "users": [
        {
          "username": "grafana-admin",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Grafana",
          "lastName": "Admin",
          "email": "grafana-admin@local.dev",
          "groups": [
            "/observability/grafana-grafana-admins"
          ],
          "credentials": [
            {
              "type": "password",
              "value": "$(env:GRAFANA_ADMIN_PASSWORD)",
              "temporary": false
            }
          ]
        },
        {
          "username": "zabbix-admin",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Zabbix",
          "lastName": "Admin",
          "email": "zabbix-admin@local.dev",
          "groups": [
            "/observability/zabbix-super-admins"
          ],
          "credentials": [
            {
              "type": "password",
              "value": "$(env:ZABBIX_ADMIN_PASSWORD)",
              "temporary": false
            }
          ]
        },
        {
          "username": "observability-admin",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Observability",
          "lastName": "Admin",
          "email": "observability-admin@local.dev",
          "groups": [
            "/observability/grafana-grafana-admins",
            "/observability/zabbix-super-admins"
          ],
          "credentials": [
            {
              "type": "password",
              "value": "$(env:OBSERVABILITY_ADMIN_PASSWORD)",
              "temporary": false
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "grafana",
          "name": "Grafana",
          "description": "Grafana OIDC client",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "bearerOnly": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "frontchannelLogout": true,
          "redirectUris": [
            "https://grafana-grafana.apps-crc.testing/login/generic_oauth"
          ],
          "webOrigins": [
            "https://grafana-grafana.apps-crc.testing"
          ],
          "attributes": {
            "client.secret.creation.time": "0",
            "oauth2.device.authorization.grant.enabled": "false",
            "oidc.ciba.grant.enabled": "false",
            "pkce.code.challenge.method": "S256"
          },
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "true",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true",
                "claim.name": "groups"
              }
            },
            {
              "name": "realm roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-realm-role-mapper",
              "consentRequired": false,
              "config": {
                "multivalued": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "realm_access.roles",
                "jsonType.label": "String"
              }
            }
          ]
        },

        {
          "clientId": "zabbix",
          "name": "Zabbix",
          "description": "Zabbix SAML client",
          "enabled": true,
          "protocol": "saml",
          "publicClient": false,
          "redirectUris": [
            "https://zabbix.apps-crc.testing/index_sso.php?acs"
          ],
          "attributes": {
            "saml.assertion.signature": "true",
            "saml.server.signature": "true",
            "saml.client.signature": "false",
            "saml.encrypt": "false",
            "saml_name_id_format": "email",
            "saml.force.post.binding": "true",
            "saml.force.name.id.format": "true",
            "saml.authnstatement": "true",
            "saml.onetimeuse.condition": "false",
            "saml_signature_canonicalization_method": "http://www.w3.org/2001/10/xml-exc-c14n#",
            "saml_single_logout_service_url_post": "https://zabbix.apps-crc.testing/index_sso.php?sls",
            "saml_assertion_consumer_url_post": "https://zabbix.apps-crc.testing/index_sso.php?acs"
          },
          "protocolMappers": [
            {
              "name": "username",
              "protocol": "saml",
              "protocolMapper": "saml-user-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "username",
                "friendly.name": "username",
                "attribute.name": "username",
                "attribute.nameformat": "Basic"
              }
            },
            {
              "name": "email",
              "protocol": "saml",
              "protocolMapper": "saml-user-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "email",
                "friendly.name": "email",
                "attribute.name": "email",
                "attribute.nameformat": "Basic"
              }
            },
            {
              "name": "firstName",
              "protocol": "saml",
              "protocolMapper": "saml-user-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "firstName",
                "friendly.name": "firstName",
                "attribute.name": "firstName",
                "attribute.nameformat": "Basic"
              }
            },
            {
              "name": "lastName",
              "protocol": "saml",
              "protocolMapper": "saml-user-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "lastName",
                "friendly.name": "lastName",
                "attribute.name": "lastName",
                "attribute.nameformat": "Basic"
              }
            },
            {
              "name": "groups",
              "protocol": "saml",
              "protocolMapper": "saml-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "attribute.name": "groups",
                "attribute.nameformat": "Basic",
                "single": "false",
                "full.path": "true"
              }
            }
          ]
        }
      ]
    }