apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli-observability
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: keycloak-config-cli
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: keycloak-config-cli
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keycloak-config-cli
          image: adorsys/keycloak-config-cli:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_URL
              value: "https://REPLACE_ME"
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-dev-initial-admin
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-dev-initial-admin
                  key: password
            - name: KEYCLOAK_SSLVERIFY
              value: "false"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "300s"
            - name: IMPORT_FILES_LOCATIONS
              value: "/config/observability-realm.json"
            - name: IMPORT_CACHE_ENABLED
              value: "false"
            - name: IMPORT_VARSUBSTITUTION_ENABLED
              value: "true"
            - name: IMPORT_BEHAVIORS_CHECKSUM_WITH_CACHE_KEY
              value: "false"
          volumeMounts:
            - name: realm-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-observability-realm