apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin