apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhbk-operator
  namespace: keycloak-ENV
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - keycloak-ENV