apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhbk-service-monitor
  namespace: keycloak-ENV
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  scrapeProtocols:
    - OpenMetricsText1.0.0
  endpoints:
    - interval: 30s
      path: /metrics
      port: management
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: tls.crt
            name: example-tls-secret
        serverName: keycloak-ENV-service.keycloak-ENV.svc.cluster.local
  selector:
    matchLabels:
      app: keycloak