apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhbk-service-monitor
  namespace: keycloak-dev
spec:
  scrapeProtocols:
    - OpenMetricsText1.0.0
  endpoints:
    - interval: 30s
      path: /metrics
      port: management
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: tls.crt
            name: example-tls-secret
        serverName: keycloak-dev-service.keycloak-dev.svc.cluster.local
  selector:
    matchLabels:
      app: keycloak