apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: rhbk-service-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    observability: platform
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: observability
spec:
  scrapeProtocols:
    - OpenMetricsText1.0.0
  selector:
    matchLabels:
      app: keycloak
      app.kubernetes.io/instance: keycloak-ENV
      app.kubernetes.io/managed-by: keycloak-operator
  endpoints:
    - interval: 30s
      path: /metrics
      port: management
      scheme: http
      scrapeTimeout: 10s
