apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhbk-service-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  scrapeProtocols:
    - OpenMetricsText1.0.0
  endpoints:
    - interval: 30s
      path: /metrics
      port: management
      scheme: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app: keycloak
