apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: keycloak-prd

configMapGenerator:
  - name: env-cfg
    literals:
      - ENV=keycloak-prd
      - KEYCLOAK_HOSTNAME=keycloak-prd.apps-crc.testing
      - SERVICE_NAME=keycloak-prd-service

replacements:
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.ENV
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
      - select:
          kind: OperatorGroup
        fieldPaths:
          - spec.targetNamespaces.0
      - select:
          kind: Keycloak
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.KEYCLOAK_HOSTNAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths: [spec.hostname.hostname]
      - select:
          kind: Route
          name: keycloak
        fieldPaths: [spec.host]
  - source:
      kind: ConfigMap
      name: env-cfg
      fieldPath: data.SERVICE_NAME
    targets:
      - select:
          kind: Keycloak
        fieldPaths: [spec.telemetry.serviceName]
      - select:
          kind: Route
          name: keycloak
        fieldPaths: [spec.to.name]
